name: base_project
description: A new Flutter project use Clean Architecture + Shorebird.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # lib base
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  auto_route: 7.8.0
  equatable: ^2.0.5
  dio: ^5.3.2
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  dartz: ^0.10.1
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  flutter_gen: ^5.3.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_dotenv: ^5.1.0
  #  list external
  shorebird_code_push: ^1.1.3
  restart_app: ^1.2.1
  fluttertoast: ^8.2.4
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner:
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - shorebird.yaml